on:
  workflow_dispatch:

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9    

      - name: Run Python script to send email
        run: python send_email1.py
        env:
          SMTP_SERVER: "${{ secrets.SMTP_SERVER }}"
          SMTP_PORT: "${{ secrets.SMTP_PORT }}"
          SMTP_USERNAME: "${{ secrets.SMTP_USERNAME }}"
          SMTP_PASSWORD: "${{ secrets.SMTP_PASSWORD }}"
          SENDER_EMAIL: "${{ secrets.SENDER_EMAIL }}"
          RECEIVER_EMAIL: "${{ secrets.RECEIVER_EMAIL }}"
